# 什么是PyTorch？

原文： https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

译者：bat67

校验者：FontTian

作者： Soumith Chintala

PyTorch是一个基于python的科学计算包，主要针对两类人群：

* 作为NumPy的替代品，可以利用GPU的性能进行计算
* 作为一个高灵活性、速度快的深度学习平台

## 张量
Tensor(张量）类似于NumPy的ndarray，但还可以在GPU上使用来加速计算

In [1]:
import torch

In [2]:
# 创建一个没有初始化的5*3矩阵：
x = torch.empty(5, 3)
print(x)

tensor([[-2.8887e-06,  4.5813e-41, -2.0362e+34],
        [ 3.0880e-41,  0.0000e+00,  0.0000e+00],
        [ 6.6216e-23,  3.6495e+03,  5.8438e+04],
        [ 2.1271e-39,  4.9572e-11,  1.2098e-23],
        [ 1.5414e-44,  9.2196e-41,  0.0000e+00]])


In [3]:
# 创建一个随机初始化矩阵：
x = torch.rand(5, 3)
print(x)

tensor([[0.8906, 0.3857, 0.1634],
        [0.7938, 0.9190, 0.2267],
        [0.1432, 0.3504, 0.4971],
        [0.2134, 0.5991, 0.2985],
        [0.3163, 0.9914, 0.4752]])


In [4]:
# 构造一个填满0且数据类型为long的矩阵:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 直接从数据构造张量：
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 或者根据已有的tensor建立新的tensor。
# 除非用户提供新的值，否则这些方法将重用输入张量的属性，例如dtype等：
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 重载 dtype!
print(x)                                      # 结果size一致

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7756,  0.3239,  1.0382],
        [-0.5475,  0.1874,  0.3670],
        [-0.6122, -0.9605,  0.5438],
        [ 0.9105,  1.4218, -0.7027],
        [-1.5001,  1.1933, -0.3516]])


In [7]:
# 获取张量的形状：

print(x.size())

torch.Size([5, 3])


注意：

torch.Size本质上还是tuple，所以支持tuple的一切操作。

## 运算
一种运算有多种语法。在下面的示例中，我们将研究加法运算。

In [8]:
# 加法：形式一

y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1461,  0.4461,  1.0513],
        [-0.1291,  0.3240,  0.5388],
        [-0.4289, -0.4316,  1.2259],
        [ 1.4848,  2.1570, -0.3741],
        [-0.5749,  1.3882,  0.1818]])


In [9]:
# 加法：形式二

print(torch.add(x, y))

tensor([[ 0.1461,  0.4461,  1.0513],
        [-0.1291,  0.3240,  0.5388],
        [-0.4289, -0.4316,  1.2259],
        [ 1.4848,  2.1570, -0.3741],
        [-0.5749,  1.3882,  0.1818]])


In [10]:
# 加法：给定一个输出张量作为参数

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.1461,  0.4461,  1.0513],
        [-0.1291,  0.3240,  0.5388],
        [-0.4289, -0.4316,  1.2259],
        [ 1.4848,  2.1570, -0.3741],
        [-0.5749,  1.3882,  0.1818]])


In [11]:
# 加法：原位/原地操作(in-place）

# adds x to y
y.add_(x)
print(y)

tensor([[ 0.1461,  0.4461,  1.0513],
        [-0.1291,  0.3240,  0.5388],
        [-0.4289, -0.4316,  1.2259],
        [ 1.4848,  2.1570, -0.3741],
        [-0.5749,  1.3882,  0.1818]])


注意：

任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x

In [12]:
# 也可以使用像标准的NumPy一样的各种索引操作：

print(x[:, 1])

tensor([ 0.3239,  0.1874, -0.9605,  1.4218,  1.1933])


In [13]:
# 改变形状：如果想改变形状，可以使用torch.view

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# 如果是仅包含一个元素的tensor，可以使用.item()来得到对应的python数值

x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2570])
-0.2570120394229889


后续阅读：

超过100种tensor的运算操作，包括转置，索引，切片，数学运算， 线性代数，随机数等，具体访问[这里](https://pytorch.org/docs/stable/torch.html)

# 桥接 NumPy
将一个Torch张量转换为一个NumPy数组是轻而易举的事情，反之亦然。

Torch张量和NumPy数组将共享它们的底层内存位置，因此当一个改变时,另外也会改变。



## 将torch的Tensor转化为NumPy数组

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
# 看NumPy数组是如何改变里面的值的：

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 将NumPy数组转化为Torch张量

In [18]:
# 看改变NumPy数组是如何自动改变Torch张量的：

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CPU上的所有张量(CharTensor除外)都支持与Numpy的相互转换。

## CUDA上的张量

In [19]:
# 张量可以使用.to方法移动到任何设备(device）上：

# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype